[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "none"

[functions."create-wallpaper"]
  timeout = 26

[functions."search-youtube"]
  timeout = 26

[functions."create-playlist"]
  timeout = 26
